name: Setup net8.0 SDK

on:
  workflow_call:

jobs:
  setup-net80:
    runs-on: windows-latest
    steps:
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'