name: Run Tests

on:
  workflow_call:
    inputs:
      source:
        description: 'Path to a specific test project, directory containing test projects, or pattern to match test projects (e.g., "tests/MyTests.csproj", "tests/", "tests/**/*Tests*.csproj")'
        required: true
        type: string
      framework:
        description: 'Test framework to run (e.g., "nunit", "xunit")'
        required: true
        type: string
      log-level:
        description: 'Log level: trace, debug, info, warning, error'
        required: false
        default: 'error'
        type: string

jobs:
  ensure-framework:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate test framework input
        id: validate
        run: |
          $framework = '${{ inputs.framework }}'
          $workflowFile = "workflows/shared/test-runners/$framework.yml"
          if (Test-Path $workflowFile) {
            Write-Host "Test framework $framework supported, workflow file found: $workflowFile"
          } else {
            Write-Error "Framework $framework is not supported or is invalid."
            exit 1
          }
        shell: pwsh

      - name: Validate log level input
        run: |
          $logLevel = '${{ inputs.log-level }}'
          $validLogLevels = @("info", "debug", "warning", "error", "trace")
          if ($validLogLevels -notcontains $logLevel) {
            Write-Error "Invalid log level: $logLevel. Supported log levels are: $validLogLevels"
            exit 1
          }
        shell: pwsh

  build:
    needs: ensure-framework
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Try download build artifacts
        id: download_artifacts
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts-${{ github.run_id }}
          path: .

      - name: Restore dependencies
        if: steps.download_artifacts.outcome != 'success'
        run: dotnet restore
        shell: pwsh

      - name: Build
        if: steps.download_artifacts.outcome != 'success'
        run: dotnet build --configuration Release --no-restore
        shell: pwsh

  run-tests:
    needs: [validate-framework, build]
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run ${{ inputs.framework }} tests
        uses: ./workflows/shared/test-runners/${{ inputs.framework }}.yml
        with:
          source: ${{ inputs.source }}
          log-level: ${{ inputs.log-level }}